name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    build:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t playwright-web .
    test:
      - uses: actions/checkout@v3
      - name: Run Playwright test
        run: docker run playwright-web