name: Playwright web automation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  playwright_build_test:
    runs-on: ubuntu-latest
    name: Job to build and run docker test for playwright
    steps:
      #Build your docker image of playwright test
    - uses: actions/checkout@v3
    - name: Build Playwright Docker Image
      run: docker build -t playwright-web .
      #Run your docker image
    - name: Run Playwright Tests
      run: docker run playwright-web